# GitHub Pages Jekyll Configuration
title: "AI Learning Students"
description: "A comprehensive educational resource for learning Artificial Intelligence - structured 14-week curriculum for undergraduate students"
url: "https://irfan-sec.github.io"
baseurl: "/ai-learning-students"

# Theme - Custom theme with layouts in _layouts/
# theme: minima
theme: null
remote_theme: null

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-sass-converter

# Navigation
header_pages:
  - index.md
  - week01.md
  - week02.md
  - week03.md
  - week04.md
  - week05.md
  - week06.md
  - week07.md
  - week08.md
  - week09.md
  - week10.md
  - week11.md
  - week12.md
  - week13.md
  - week14.md

# Sass/SCSS configuration
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/